DB_URL = "postgres://localhost/mal_track_#{ENV['RACK_ENV']}".freeze
DataMapper.setup(:default, ENV['DATABASE_URL'] || DB_URL)
DataMapper.auto_migrate! if ENV['RACK_ENV'] == 'test'
DataMapper.finalize

# Seed database
rules = [{
            fever: 0,
            headache: 0,
            nausea: 0,
            vomiting: 0,
            jaundice: 0,
            enlarged_liver: 0,
            joint_pain: 0,
            body_weakness: 0,
            dizziness: 0.5,
            loss_of_apetite: 0,
            mp: 0,
            type: 0
          },
         {
           fever: 0.25,
           headache: 0,
           nausea: 0,
           vomiting: 0,
           jaundice: 0,
           enlarged_liver: 0,
           joint_pain: 0.25,
           body_weakness: 0.25,
           dizziness: 0.5,
           loss_of_apetite: 0.5,
           mp: 0.25,
           type: 1
         },
         {
           fever: 0.5,
           headache: 0.25,
           nausea: 0,
           vomiting: 0,
           jaundice: 0,
           enlarged_liver: 0,
           joint_pain: 0,
           body_weakness: 0.5,
           dizziness: 0.5,
           loss_of_apetite: 0.5,
           mp: 0.25,
           type: 2,
         },
         {
           fever: 0.75,
           headache: 0,
           nausea: 0,
           vomiting: 0,
           jaundice: 0,
           enlarged_liver: 0,
           joint_pain: 0.5,
           body_weakness: 0.5,
           dizziness: 0,
           loss_of_apetite: 0,
           mp: 0.5,
           type: 3
         },
         {
           fever: 0.25,
           headache: 0,
           nausea: 0,
           vomiting: 0.25,
           jaundice: 0,
           enlarged_liver: 0,
           joint_pain: 0.25,
           body_weakness: 0.25,
           dizziness: 0.25,
           loss_of_apetite: 0.5,
           mp: 0.25,
           type: 1
         },
         {
           fever: 0,
           headache: 0.25,
           nausea: 0.25,
           vomiting: 0,
           jaundice: 0,
           enlarged_liver: 0,
           joint_pain: 0,
           body_weakness: 0,
           dizziness: 0.25,
           loss_of_apetite: 0,
           mp: 0,
           type: 0
         },
         {
           fever: 0,
           headache: 0,
           nausea: 0.25,
           vomiting: 0.25,
           jaundice: 0,
           enlarged_liver: 0,
           joint_pain: 0.5,
           body_weakness: 0.5,
           dizziness: 0.25,
           loss_of_apetite: 0.25,
           mp: 0.25,
           type: 2
         },
         {
           fever: 0.25,
           headache: 0.25,
           nausea: 0.25,
           vomiting: 0.25,
           jaundice: 0.25,
           enlarged_liver: 0.25,
           joint_pain: 0.25,
           body_weakness: 0.25,
           dizziness: 0.25,
           loss_of_apetite: 0.25,
           mp: 0.25,
           type: 1
         },
         {
           fever: 0.25,
           headache: 0,
           nausea: 0.25,
           vomiting: 0.25,
           jaundice: 0,
           enlarged_liver: 0.5,
           joint_pain: 0.25,
           body_weakness: 0.25,
           dizziness: 0.5,
           loss_of_apetite: 0.25,
           mp: 0.25,
           type: 1
         },
         {
           fever: 0.25,
           headache: 0,
           nausea: 0,
           vomiting: 0,
           jaundice: 0,
           enlarged_liver: 0,
           joint_pain: 0.25,
           body_weakness: 0.25,
           dizziness: 0.5,
           loss_of_apetite: 0.5,
           mp: 0.25,
           type: 0
         },
         {
           fever: 0.5,
           headache: 0.5,
           nausea: 0.5,
           vomiting: 0.5,
           jaundice: 0.5,
           enlarged_liver: 0.5,
           joint_pain: 0.5,
           body_weakness: 0.75,
           dizziness: 0.5,
           loss_of_apetite: 0.5,
           mp: 0.25,
           type: 3
         },
         {
           fever: 0.25,
           headache: 0.5,
           nausea: 0.25,
           vomiting: 0.5,
           jaundice: 0.25,
           enlarged_liver: 0.5,
           joint_pain: 0.25,
           body_weakness: 0.5,
           dizziness: 0.25,
           loss_of_apetite: 0,
           mp: 0.25,
           type: 2
         },
         {
           fever: 0,
           headache: 0.25,
           nausea: 0.25,
           vomiting: 0.25,
           jaundice: 0,
           enlarged_liver: 0,
           joint_pain: 0,
           body_weakness: 0.25,
           dizziness: 0,
           loss_of_apetite: 0.25,
           mp: 0.25,
           type: 1
         },
         {
           fever: 0.5,
           headache: 0.5,
           nausea: 0.25,
           vomiting: 0.5,
           jaundice: 0.5,
           enlarged_liver: 0.5,
           joint_pain: 0.5,
           body_weakness: 0.5,
           dizziness: 0.25,
           loss_of_apetite: 0.25,
           mp: 0.5,
           type: 2
         },
         {
           fever: 0,
           headache: 0,
           nausea: 0,
           vomiting: 0.25,
           jaundice: 0,
           enlarged_liver: 0,
           joint_pain: 0,
           body_weakness: 0.5,
           dizziness: 0,
           loss_of_apetite: 0.5,
           mp: 0.25,
           type: 2
         },
         {
           fever: 0.75,
           headache: 0.25,
           nausea: 0,
           vomiting: 0.25,
           jaundice: 0.5,
           enlarged_liver: 0.25,
           joint_pain: 0,
           body_weakness: 0.75,
           dizziness: 0.5,
           loss_of_apetite: 0,
           mp: 0.25,
           type: 3
         },
         {
           fever: 0,
           headache: 0.75,
           nausea: 0.25,
           vomiting: 0.25,
           jaundice: 0,
           enlarged_liver: 0.25,
           joint_pain: 0,
           body_weakness: 0.25,
           dizziness: 0.75,
           loss_of_apetite: 0,
           mp: 0.25,
           type: 3
         },
         {
           fever: 0.25,
           headache: 0.75,
           nausea: 0.25,
           vomiting: 0,
           jaundice: 0.5,
           enlarged_liver: 0.5,
           joint_pain: 0.25,
           body_weakness: 0.5,
           dizziness: 0.75,
           loss_of_apetite: 0.75,
           mp: 0.5,
           type: 3
         },
         {
           fever: 0.25,
           headache: 0.25,
           nausea: 0.25,
           vomiting: 0.25,
           jaundice: 0,
           enlarged_liver: 0,
           joint_pain: 0.25,
           body_weakness: 0.25,
           dizziness: 0.25,
           loss_of_apetite: 0.25,
           mp: 0.25,
           type: 1
         },
         {
           fever: 0.75,
           headache: 0.5,
           nausea: 0.5,
           vomiting: 0.5,
           jaundice: 0.5,
           enlarged_liver: 0.5,
           joint_pain: 0.5,
           body_weakness: 0.5,
           dizziness: 0.5,
           loss_of_apetite: 0.5,
           mp: 0.25,
           type: 3
         }
    ]

rules.each do |rule|
  Rule.create(rule)
end
